# frozen_string_literal: true

source "https://rubygems.org"

gem "action_cable_client"
gem "activesupport"
gem "pry"

group :development do
  gem "rubocop", require: false
  gem "rubocop-performance", require: false
end
