AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - bin/**/*
    - db/schema.rb
    - node_modules/**/*

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*

Metrics/BlockLength:
  Exclude:
    - config/environments/*
    - config/routes.rb

Metrics/LineLength:
  Exclude:
    - db/migrate/**/*
  IgnoredPatterns:
    - \#\s

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*

Naming/UncommunicativeMethodParamName:
  Enabled: false

Security/Eval:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Send:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
